name: Ping URL every 55 minutes

on:
  schedule:
    - cron: '*/14 * * * *'  # Every 55 minutes
  workflow_dispatch:       # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests
        
      - name: Run script
        run: python pinger.py

